service: WebpageBackend

frameworkVersion: '3'

provider:
  architecture: arm64
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:*"
        - "logs:*"
        - "s3:*"
        - "iam:PassRole"
      Resource: "*"
  region: eu-west-1
  stage: dev
  environment:
    S3_BUCKET_NAME: api.itbock.de
    S3_TOKEN_PATH: tokens/

functions:
  generateToken:
    handler: build/lambda.generateTokenHandler
    events:
      - http:
          path: generate-token
          method: post
          cors: true
  validateToken:
    handler: build/lambda.validateTokenHandler
    events:
      - http:
          path: validate-token
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000

package:
  exclude:
    - ./**
  include:
    - build/**
